### ISSUE TITLE
Add vendored libs to LFS

### ISSUE THREAD

**Issue by rminderhoud** [tafia/blpapi-rs#2]
Hi @tafia, thanks for the work on this crate. I'm going to be using this so hopefully can start contributing some things in the next few weeks.

A small issue to start, I noticed that the `*.so` `*.dll` and `*.lib` in the `vendored/` directories are not tracked by LFS and are saved in the repo directly. I fixed this in a local fork but it appears github does not support pushing LFS objects in public forks so unfortunately it means you would have to do it.

In general I find it's better to keep binaries out of the main repo because it causes issues with binary file issues (already had that issue when cloning this repo).

Steps to remove:
- Remove these files from git
- Commit changes
- Add back these files in addition to a `.gitattributes` file

.gitattributes
```
# Windows libraries
*.[Dd][Ll][Ll] filter=lfs diff=lfs merge=lfs -text
*.[Ll][Ii][Bb] filter=lfs diff=lfs merge=lfs -text

# Linux libraries
*.[Ss][Oo] filter=lfs diff=lfs merge=lfs -text
```

**Comment by tafia** [comment]
> I'm going to be using this so hopefully can start contributing some things in the next few weeks.

Awesome!

Regarding LFS, thanks for the suggestion, I'll try doing that.

**Comment by tafia** [comment]
Done, I'm not familiar with LFS, did it work?

**Comment by rminderhoud** [comment]
Ah shoot, I missed a step because I thought `git lfs` was already enabled but I think needed to run the `git lfs install` command before adding the binary files back.

**Comment by tafia** [comment]
Should be good now!
